name: release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: composer install
      run: make composer
    - name: add version
      env:
        TAGNAME: ${{ github.ref }}
      run: |
        sed -i -e "s/{release version}/${TAGNAME}/g" shifter-github.php
    - name: create archive
      run: make archive
    - name: upload
      env:
        PACKAGE_NAME: "shifter-github"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAGNAME: ${{ github.ref }}
        GOPATH: /home/runner/go
      run: |
        go get -u github.com/tcnksm/ghr
        ${GOPATH}/bin/ghr -b "${PACKAGE_NAME} ${TAGNAME}" -replace ${TAGNAME} ${PACKAGE_NAME}.zip
